### ISSUE TITLE
Dark/Light mode

### ISSUE THREAD

**Issue by invaders-xx** [stechstudio/filament-impersonate#11]
Hi,

Many thanks for this package. It would be great if the banner style automatically switches when filament dark mode is enabled and toggled.

**Comment by jszobody** [comment]
The auto-injected banner is dark by default. I just added a bottom-border so that it looks a bit better above the rest of the UI:

<img width="1510" alt="CleanShot 2022-04-29 at 08 36 18@2x" src="https://user-images.githubusercontent.com/203749/165945593-289d5fb5-2e85-4dc7-bdd0-820828e55975.png">

That what you had in mind?

**Comment by Saifallak** [comment]
@jszobody nope, i guess he means the banner toggles light/dark with filament

**Comment by jszobody** [comment]
@Saifallak I designed the banner to be "dark" all the time. Even when filament is in light mode, the impersonation banner at the top is dark. So what's there to toggle? I can't imagine you'd want the banner to be _light_ when filament goes dark??

**Comment by Saifallak** [comment]
nope i meant when :
- filment is dark the banner is dark

![image](https://user-images.githubusercontent.com/6053156/166099142-2fc48e01-c33e-425d-b9d5-ff4bf93e0134.png)


- and when filment is light, the banner is light.
![image](https://user-images.githubusercontent.com/6053156/166099193-e5be08ec-8c14-4cba-8684-bcae5d604fe4.png)

**Comment by jszobody** [comment]
Happy to review a PR if someone wants to take a stab, going to close this for now.

**Comment by jszobody** [comment]
This is now done in `2.13`
