### ISSUE TITLE
Bump version to Laravel 10

### ISSUE THREAD

**Issue by ClausMunch** [stechstudio/filament-impersonate#31]
Hi, could you bump the version to support Laravel 10?

**Comment by jszobody** [comment]
Hi there. This package doesn't specify a Laravel version at all, see the composer.json file. I think it should install just fine. If you're having trouble can you show me the error message?

**Comment by ClausMunch** [comment]
Problem 1
    - lab404/laravel-impersonate 1.7.0 requires laravel/framework ^6.0 | ^7.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^10.0).
    - lab404/laravel-impersonate[1.7.1, ..., 1.7.2] require laravel/framework ^6.0 | ^7.0 | ^8.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^10.0).
    - lab404/laravel-impersonate 1.7.3 requires laravel/framework ^6.0 | ^7.0 | ^8.0 | ^9.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^10.0).
    - Root composer.json requires saade/filament-laravel-log ^1.1 -> satisfiable by saade/filament-laravel-log[v1.1.0, v1.1.1, v1.1.2].
    - lab404/laravel-impersonate 1.7.4 requires laravel/framework ^6.0 | ^7.0 | ^8.0 | ^9.0 | ^10.0 -> satisfiable by laravel/framework[v10.0.0, ..., 10.x-dev].
    - Only one of these can be installed: illuminate/contracts[dev-master, v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev], laravel/framework[v10.0.0, ..., 10.x-dev]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
    - stechstudio/filament-impersonate 2.11 requires lab404/laravel-impersonate ^1.7 -> satisfiable by lab404/laravel-impersonate[1.7.0, ..., 1.7.4].
    - saade/filament-laravel-log[v1.1.0, ..., v1.1.2] require illuminate/contracts ^9.0 -> satisfiable by illuminate/contracts[v9.0.0-beta.1, ..., 9.x-dev].
    - Root composer.json requires stechstudio/filament-impersonate ^2.11 -> satisfiable by stechstudio/filament-impersonate[2.11].

**Comment by ObjectRetros** [comment]
I run into the same issue. I assume its the lab404 dependency which doesn't support Laravel 10 where as this package relies on lab404

**Comment by jszobody** [comment]
I just installed a fresh Laravel 10 app, fresh Filament (it installed `2.17.3`), and then installed this package. It worked just fine, no issues with Laravel 10.

Make sure you're allowing composer to update all dependencies with `--with-all-dependencies`. 

@ObjectRetros the lab404 dependency has already been updated for Laravel 10. They released 1.7.4 with Laravel 10 support. Since this impersonate package depends on `^1.7` then it should be fine.

@ClausMunch In the error you posted, it looks like `saade/filament-laravel-log` is your problem. That package is requiring `illuminate/contracts` at v9.0, conflicting with Laravel 10. You can see they haven't updated their package yet for Laravel 10:

https://github.com/saade/filament-laravel-log/blob/9e4167d6115b764d5c6fd58a04d2e8f317fa2960/composer.json#L21

You'll need to go ask them to update, or remove the package.

I'm closing this for now, since I've verified the package installs in a Laravel 10 without issues. Feel free to update/reopen if someone hits a specific Laravel 10 issue with this package.
